---
layout: default
title: "Population Structure"
parent: Low Coverage
grand_parent: Whole Genome Sequencing
has_children: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Population Structure

Intro to methods

# Vignette

Perform population structure analyses with [PCAngsd](http://www.popgen.dk/software/index.php/PCAngsd),
[PLINK PCA](https://www.cog-genomics.org/plink/1.9/strat), [NGSadmix](http://www.popgen.dk/software/index.php/NgsAdmix), and [popVAE](https://github.com/kr-colab/popvae).

[Example with Pacific herring](http://htmlpreview.github.com/?https://github.com/MarineOmics/Template_Site_1/blob/main/population_genetics/vignettes/Pacific_Herring_population_strucutre.html)



```{r, echo=FALSE,eval=FALSE}
library(knitr)
my.jekyll.site <- "marineomics.github.io/Template_Site_1/"
KnitPost <- function(input, base.url = my.jekyll.site) {
  opts_knit$set(base.url = base.url)
  fig.path <- paste0("images/", sub(".Rmd$", "", basename(input)), "/")
  opts_chunk$set(fig.path = fig.path)
  opts_chunk$set(fig.cap = "center")
  render_jekyll()
  knit(input, envir = parent.frame())
}

KnitPost("C:/Users/jmcgirr/Documents/GitHub/MarineOmics/Template_Site_1.github.io/population_genetics/population_structure.Rmd")

```

