---
hide:
  - navigation
---
---
title: "Contributions"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# How to contribute new material to the MarineOmics.github.io website
If you are interested in submitting new content to the
MarineOmics.github.io website, we have a [guide](ADMIN_01_submissions_instructions.html) for you!
While the website managers will work with you to help prepare and publish your new
page, this guide can be a useful resource as you develop your content. The guide provides general instructions as well as examples of how to build specific features (eg., tables, code chunks). Prior to developing new pages, please contact the current Website Manager Jason Johns (jasonjohns[at]ucsb.edu). Do not hesitate to reach out with any other questions, comments, or features you'd like added to the guide.


# Active Contributors 
#### [Katherine Silliman, PhD](https://ksilliman.weebly.com/), NOAA Atlantic Oceanographic and Meteorological Lab - katherine.silliman[at]noaa.gov (Working Group Co-leader) {.unlisted .unnumbered}
#### [Sam Bogan](http://www.hofmannlab.com/sam-bogan.html), UC-Santa Barbara - snbogan[at]ucsb.edu (Working Group Co-leader) {.unlisted .unnumbered}
#### Tait Algayer, Washington State University {.unlisted .unnumbered}
#### Len Aguila, Texas A&M University Galveston {.unlisted .unnumbered}
#### [Danielle Davenport, PhD](https://www.researchgate.net/profile/Danielle-Davenport-2), Fisheries and Oceans Canada {.unlisted .unnumbered}  
#### Stephen Gaughran, PhD, Princeton University {.unlisted .unnumbered}
#### Thea Gessler, Iowa State University {.unlisted .unnumbered}
#### [Joanna Griffiths, PhD](https://joannasgriffiths.wordpress.com/), UC-Davis {.unlisted .unnumbered}
#### Jason Johns, UC-Santa Barbara - jasonjohns[at]ucsb.edu (Website Manager) {.unlisted .unnumbered}
#### Sarit Truskey, Northeastern University {.unlisted .unnumbered}

<br>

### Faculty Advisors {.unlisted .unnumbered}
#### [Katie Lotterhos, PhD](https://whiteheadresearch.wordpress.com/), Northeastern University {.unlisted .unnumbered}
#### [Jon Puritz, PhD](https://www.marineevoeco.com/), University of Rhode Island {.unlisted .unnumbered}
#### [Steven Roberts, PhD](http://faculty.washington.edu/sr320/?page_id=10850), University of Washington {.unlisted .unnumbered}

<br>

# Former Contributors 
#### Natalie Ameral, University of Rhode Island & RI Dept. of Environmental Management {.unlisted .unnumbered}
#### [Alan Downey-Wall](https://cos.northeastern.edu/people/alan-downey-wall/), Northeastern University {.unlisted .unnumbered}
#### Megan Guidry, University of Rhode Island {.unlisted .unnumbered}
#### Jecy Klinkam, College of William and Mary (Intern) {.unlisted .unnumbered}
#### Nicolas Lou, Cornell University {.unlisted .unnumbered}
#### Kaitlin Macaranas, CSU-Bakersfield (Intern) {.unlisted .unnumbered}
#### Chris Mantegna, University of Washington (Intern)  {.unlisted .unnumbered}
#### [Joe McGirr, PhD](https://joemcgirr.github.io/), Thermo Fisher Scientific {.unlisted .unnumbered}
#### [Hanny Rivera, PhD](https://www2.whoi.edu/staff/hrivera/), Woods Hole Oceanographic Institute  {.unlisted .unnumbered}
#### [Sara Schaal](https://schaals.wixsite.com/smschaal), NOAA Alaska Fisheries Science Center {.unlisted .unnumbered} 
#### [Andrew Whitehead, PhD](https://whiteheadresearch.wordpress.com/), UC-Davis {.unlisted .unnumbered}
#### [Sara Wuitchik, PhD](https://sjswuitchik.weebly.com/), Mount Royal University {.unlisted .unnumbered}