---
title: "Contributors"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Original Working Group Members  

#### [Katherine Silliman, PhD](https://ksilliman.weebly.com/), South Carolina Dept. of Natural Resources - sillimank[at]dnr.sc.gov {.unlisted .unnumbered}
#### [Sam Bogan](http://www.hofmannlab.com/sam-bogan.html), UC-Santa Barbara -snbogan[at]ucsb.edu {.unlisted .unnumbered}
#### [Alan Downey-Wall](https://cos.northeastern.edu/people/alan-downey-wall/), Northeastern University {.unlisted .unnumbered}
#### Chris Mantegna, University of Washington (Intern)  {.unlisted .unnumbered}
#### [Danielle Davenport](https://www.researchgate.net/profile/Danielle-Davenport-2), University of Queensland {.unlisted .unnumbered}  
#### [Hanny Rivera, PhD](https://www2.whoi.edu/staff/hrivera/), Woods Hole Oceanographic Institute  {.unlisted .unnumbered}
#### Jecy Klinkam, College of William and Mary (Intern) {.unlisted .unnumbered}
#### [Joanna Griffiths, PhD](https://joannasgriffiths.wordpress.com/), UC-Davis {.unlisted .unnumbered}
#### Jason Johns, UC-Santa Barbara (Website Manager) {.unlisted .unnumbered}
#### [Joe McGirr, PhD](https://joemcgirr.github.io/), UC-Davis {.unlisted .unnumbered}
#### Kaitlin Macaranas, CSU-Bakersfield (Intern) {.unlisted .unnumbered}
#### Megan Guidry, University of Rhode Island {.unlisted .unnumbered}
#### Natalie Ameral, University of Rhode Island & RI Dept. of Environmental Management {.unlisted .unnumbered}  
#### Nicolas Lou, Cornell University {.unlisted .unnumbered}
#### [Sara Schaal](https://schaals.wixsite.com/smschaal), Northeastern University {.unlisted .unnumbered} 
#### [Sara Wuitchik, PhD](https://sjswuitchik.weebly.com/), Harvard University {.unlisted .unnumbered}


### Faculty Advisors {.unlisted .unnumbered}
#### [Andrew Whitehead, PhD](https://whiteheadresearch.wordpress.com/), UC-Davis {.unlisted .unnumbered}
#### [Jon Puritz, PhD](https://www.marineevoeco.com/), University of Rhode Island {.unlisted .unnumbered}
#### [Steven Roberts, PhD](http://faculty.washington.edu/sr320/?page_id=10850), University of Washington {.unlisted .unnumbered}


