---
title: Panel Seminars
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


To facilitate discussions about practices and pitfalls in applying 'omics to non-model systems, we hosted Q & A panel seminars with experts on topics ranging from RADseq, population genomics with WGS, and transcriptomics in May-June 2021. 3-5 expert panelists discussed each topic, with questions coming from the working group and the audience. Videos are available on YouTube!

## Seminar Schedule {.unlisted .unnumbered}  

| Date        | Topic       | Panelists     | Video     |
| :---        | :---        | :---          | :---      |
| May 7         | GBS/RADseq genotyping pipelines     | [Melanie LaCava](https://melanielacava.weebly.com/), [Alicia Mastretta-Yanes](http://mastrettayanes-lab.org/), [Isaac Overcast](https://isaacovercast.github.io/), [Jon Puritz](https://www.marineevoeco.com/)   | [View video](https://www.youtube.com/watch?v=C74GBESeIq4)     |
| May 21       |  WGS genotyping (low and high coverage)     | [Jeffrey Good](http://www.thegoodlab.org/), [Mikhail "Misha" Matz](https://matzlab.weebly.com/), [Noah Reid](http://nreid.github.io/), [Tim Sackton](https://scholar.harvard.edu/tsackton), [Nina Overgaard Therkildsen](https://www.therkildsenlab.com/) | [View Video](https://www.youtube.com/watch?v=ObJ3OT3dwSw)    |
| June 4       |  Population genomic analyses and filtering data     | [Zach Gompert](https://gompertlab.com/), [Morgan Kelly](http://www.morgankelly.biology.lsu.edu/), [Katie Lotterhos](https://sites.google.com/site/katielotterhos/home), [Jeff Ross-Ibarra](https://rilab.ucdavis.edu/) |  [View Video](https://youtu.be/dZyuqVEGPMo)   |
| June 18       |  RNAseq (experimental design through differential expression)     | [Ana Conesa](http://conesalab.org/), [Sarah Davies](http://sites.bu.edu/davieslab/), [Martin Hölzer](https://hoelzer-lab.github.io/), [Joanna Kelley](https://labs.wsu.edu/genomes/), [Harold Pimentel](https://pimentellab.com/)     |  [View Video](https://youtu.be/-gQ59m2cck0)   |



