---
title: 'Instructions for developing new pages to the MarineOmics webpage'
bibliography: RCN_site-Nov05.bib
---


```{r setup, message = FALSE, echo = FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
library(knitcitations)
library(kableExtra)
opts_chunk$set(fig.width = 10,
               fig.height = 5,
               cache = FALSE)
cite_options(citation_format = "pandoc", max.names = 3, style = "html", 
             hyperlink = "to.doc")
```


## Overview

This is a guide for creating a new page for the website. Of course, the website managers will work with anyone who develops new content to answer questions and publish the site, but this can be used as a resource as you develop your page. In this guide are general instructions as well as examples of how to build specific features. If there is anything else you would like to see on this guide please contact Jason Johns (jasonjohns[at]ucsb.edu). Of course, do not hesitate to reach out with any other questions or comments as well.

\*\* Before publishing any content, please contact Jason Johns (jasonjohns[at]ucsb.edu) so we can have working group contributors review the page.

This website is published through Github Pages directly from the [MarineOmics github repository](https://github.com/MarineOmics/marineomics.github.io). In short, each page of the website is rendered as an .html from an RMarkdown (.Rmd) document. The two most important files for publishing the website are the .site_yml ("the yaml file") and the index.Rmd/index.html. 

**.site_yml**: the 'under the hood' backbone of the website, where things like the visual appearance of the website the navigation bar are built

**index.html**: rendered from index.Rmd - the home page from which all other pages branch

\* The website manager will help modify the index.html and .site_yml files for your page when the time comes, so you don't need to know exactly how they work, but it's good to know what they are at a basic level.


# R Markdown basics
The rendered .Rmd and .html files for each page on this site can be seen in the [MarineOmics github repository](https://github.com/MarineOmics/marineomics.github.io). If you don't have much experience with RStudio, it's quite intuitive with a shallow learning curve and many existing online resources for using it.

*Note: it's a good idea to look at existing .Rmd scripts to see examples of how a particular feature can be accomplished, such as citing references, linking a website, building a table, incorporating figures, etc. We will explicitly go over some of those feautures below, but there are many other bells and whistles that can be explored through other resources online.*

## Initial Page Setup
- caching
- installing & loading packages
- etc.

## Formatting
- text vs. code chunks, how to include code on the page or not, include output or not, etc.
- navigation bar on the left, font size, bold, italics, etc
- in-text citations, hyperlinks

## Making a table - Katherine/Sam

## Including a figure - Katherine/Sam

## Including an image - Katherine/Sam

## Running code in another language such as bash - Katherine/Sam

## References

