<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Megha Prasad">
<meta name="dcterms.date" content="2026-07-30">

<title>Comparing mRNA structures between alleles using RNAdistance – MarineOmics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./FUN_02_DNA_methylation.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-a26f3680889bc016604be2101547878f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="site_libs/quarto-diagram/mermaid.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="tutorial.css">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">MarineOmics</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./ADMIN_03_panels.html"> 
<span class="menu-text">Panel Seminars</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/MarineOmics/marineomics.github.io/discussions"> 
<span class="menu-text">Discussion Forum</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./MOL_01_RNAdist_tutorial.html">Molecular Modeling</a></li><li class="breadcrumb-item"><a href="./MOL_01_RNAdist_tutorial.html">Comparing mRNA structures between alleles using RNAdistance</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Contributions</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ADMIN_01_submissions_instructions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Instructions for developing new pages for the MarineOmics webpage</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ADMIN_02_contributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Contributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ADMIN_05_major_versions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Major Versions</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Best Principles</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ADMIN_04_best_principles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Best Principles in Genomics Research</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Population Genomics</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./POP_01_choosing_population_genetics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Choosing a Population Genomics Approach</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./POP_04_WGS_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Whole Genome Resequencing for Population Genomics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./POP_02_RADseq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">RADseq</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./POP_03_poolseq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PoPoolation Pipeline</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./RDAtraitPredictionTutorial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">RDA trait prediction tutorial</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./POP_08_PCA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PCA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./POP_09_aDNA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ancient and Degraded DNA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./POP_10_Signatures_of_Selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">A MarineOmics overview of methods to detect signatures of selection</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Functional Genomics</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./FUN_01_DGE_comparison_v2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Fitting Multifactorial Models of Differential Expression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./FUN_02_DNA_methylation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DNA Methylation Assessment</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Molecular Modeling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./MOL_01_RNAdist_tutorial.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Comparing mRNA structures between alleles using RNAdistance</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Genome-Phenome</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
 <span class="menu-text">Coming soon!</span>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#citation" id="toc-citation" class="nav-link active" data-scroll-target="#citation">Citation</a></li>
  <li><a href="#target-audience" id="toc-target-audience" class="nav-link" data-scroll-target="#target-audience">Target audience</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#pipeline-overview" id="toc-pipeline-overview" class="nav-link" data-scroll-target="#pipeline-overview">Pipeline overview</a></li>
  <li><a href="#prerequisites" id="toc-prerequisites" class="nav-link" data-scroll-target="#prerequisites">Prerequisites</a></li>
  <li><a href="#getting-example-data" id="toc-getting-example-data" class="nav-link" data-scroll-target="#getting-example-data">Getting example data</a></li>
  <li><a href="#step-1-preparing-the-input" id="toc-step-1-preparing-the-input" class="nav-link" data-scroll-target="#step-1-preparing-the-input">Step 1: Preparing the input</a></li>
  <li><a href="#step-2-generating-reference-and-alternate-sequences" id="toc-step-2-generating-reference-and-alternate-sequences" class="nav-link" data-scroll-target="#step-2-generating-reference-and-alternate-sequences">Step 2: Generating reference and alternate sequences</a></li>
  <li><a href="#step-3-folding-sequences-with-rnafold" id="toc-step-3-folding-sequences-with-rnafold" class="nav-link" data-scroll-target="#step-3-folding-sequences-with-rnafold">Step 3: Folding sequences with RNAfold</a></li>
  <li><a href="#step-4-comparing-structures-with-rnadistance" id="toc-step-4-comparing-structures-with-rnadistance" class="nav-link" data-scroll-target="#step-4-comparing-structures-with-rnadistance">Step 4: Comparing structures with RNAdistance</a></li>
  <li><a href="#worked-example-a-single-variant-end-to-end" id="toc-worked-example-a-single-variant-end-to-end" class="nav-link" data-scroll-target="#worked-example-a-single-variant-end-to-end">Worked example: a single variant end-to-end</a></li>
  <li><a href="#step-5-normalizing-the-distance-score" id="toc-step-5-normalizing-the-distance-score" class="nav-link" data-scroll-target="#step-5-normalizing-the-distance-score">Step 5: Normalizing the distance score</a></li>
  <li><a href="#practical-notes-and-caveats" id="toc-practical-notes-and-caveats" class="nav-link" data-scroll-target="#practical-notes-and-caveats">Practical notes and caveats</a></li>
  <li><a href="#where-to-go-from-here" id="toc-where-to-go-from-here" class="nav-link" data-scroll-target="#where-to-go-from-here">Where to go from here</a></li>
  <li><a href="#session-info" id="toc-session-info" class="nav-link" data-scroll-target="#session-info">Session info</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/MarineOmics/marineomics.github.io/edit/main/MOL_01_RNAdist_tutorial.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/MarineOmics/marineomics.github.io/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<div style="background-color: #f8f9fa; border-left: 4px solid #6c757d; padding: 8px 14px; margin-bottom: 16px; font-size: 0.85em;">
  Last rendered: July 2026 — see <a href="ADMIN_05_major_versions.html">Major Versions</a> for full environment details.
</div>

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./MOL_01_RNAdist_tutorial.html">Molecular Modeling</a></li><li class="breadcrumb-item"><a href="./MOL_01_RNAdist_tutorial.html">Comparing mRNA structures between alleles using RNAdistance</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Comparing mRNA structures between alleles using RNAdistance</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Megha Prasad </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 30, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="citation" class="level2">
<h2 class="anchored" data-anchor-id="citation">Citation</h2>
<p><a href="https://marineomics.github.io/#How_to_Cite">How to cite</a></p>
</section>
<section id="target-audience" class="level2">
<h2 class="anchored" data-anchor-id="target-audience">Target audience</h2>
<p>This page is for people who have a set of candidate variants (from a GEA, an FST outlier scan, a GWAS, or elsewhere) and want to check whether those variants change how the mRNA folds. You should be comfortable on the command line and have some basic R or Python. No prior experience with RNA structure prediction is needed. For the full documentation of the tools used here, see the <a href="https://www.tbi.univie.ac.at/RNA/">ViennaRNA documentation</a> (<span class="citation" data-cites="Lorenz2011-yw">Lorenz et al. (<a href="#ref-Lorenz2011-yw" role="doc-biblioref">2011</a>)</span>).</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>mRNA folds into secondary structures, and those structures affect translation efficiency, mRNA stability, subcellular localization, and interactions with RNA-binding proteins. This means sequence changes can affect the mRNA even when they don’t change the protein it encodes. Synonymous variants in particular have often been treated as neutral in adaptation studies, but a growing body of work suggests that some synonymous variants under selection may be acting through changes in mRNA structure rather than through the protein.</p>
<p>One way to check whether a variant might be doing this is to fold the reference and alternate sequences separately and see how different the resulting structures are. If they look identical, structure is probably not the story. If they look very different, it’s worth following up on.</p>
<p>This page walks through how to do that comparison end-to-end. We use two tools from the ViennaRNA package: <code>RNAfold</code>, which predicts the minimum free energy (MFE) structure of an RNA sequence, and <code>RNAdistance</code>, which quantifies how different two structures are. At the end we go through how to normalize the resulting distance so that scores are comparable across genes of different lengths.</p>
<p>Note that this tutorial compares structures at a single temperature. If your question specifically involves comparing structures across temperatures (thermal stability, for example), the same tools apply but the interpretation of the normalized score changes.</p>
</section>
<section id="pipeline-overview" class="level2">
<h2 class="anchored" data-anchor-id="pipeline-overview">Pipeline overview</h2>
<p>The workflow has five main steps: preparing your variant list, generating the reference and alternate sequences, folding each sequence with <code>RNAfold</code>, comparing the resulting structures with <code>RNAdistance</code>, and normalizing the raw distance so it’s comparable across genes.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    A[Variant list&lt;br/&gt;transcript coords] --&gt; B[Generate ref &amp;&lt;br/&gt;alt sequences]
    B --&gt; C[Fold with&lt;br/&gt;RNAfold]
    C --&gt; D[Compare with&lt;br/&gt;RNAdistance]
    D --&gt; E[Normalize by&lt;br/&gt;transcript length]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Each of these is covered in its own step below.</p>
</section>
<section id="prerequisites" class="level2">
<h2 class="anchored" data-anchor-id="prerequisites">Prerequisites</h2>
<p>To follow along you will need:</p>
<ul>
<li><strong>ViennaRNA 2.x</strong>, which provides the <code>RNAfold</code> and <code>RNAdistance</code> executables. Installation instructions are at <a href="https://www.tbi.univie.ac.at/RNA/">https://www.tbi.univie.ac.at/RNA/</a>. If you are working on a compute cluster, ViennaRNA is often available as a module already, so it’s worth running <code>module avail RNA</code> before installing it yourself.</li>
<li><strong>Transcript sequences</strong> for the genes of interest, in FASTA format.</li>
<li><strong>A list of variants</strong> with positions in transcript coordinates (not genome coordinates). If your variants are in genome coordinates, they will need to be converted first (see Step 1).</li>
<li>Basic experience with the command line, plus R or Python for input preparation.</li>
</ul>
<p>We assume throughout that all variants are biallelic SNPs. Indels and multiallelic sites need extra handling that isn’t covered here.</p>
</section>
<section id="getting-example-data" class="level2">
<h2 class="anchored" data-anchor-id="getting-example-data">Getting example data</h2>
<p>If you don’t have your own dataset yet and want to try the pipeline, most of the input you need is available from public repositories:</p>
<ul>
<li><strong>Transcript sequences</strong> can be downloaded from <a href="https://www.ensembl.org/">Ensembl</a> or <a href="https://www.ncbi.nlm.nih.gov/refseq/">NCBI RefSeq</a>. Both provide transcript FASTAs by species and by gene, and either the GRCh38 cDNA fasta from Ensembl or the RefSeq mRNA fasta for your species of interest is a reasonable starting point.</li>
<li><strong>Reference annotations (GTF/GFF)</strong> for coordinate conversion are also available from Ensembl and NCBI, and typically come with the transcript FASTAs.</li>
<li><strong>Variant data</strong> for testing purposes can be pulled from public sources like <a href="https://www.ncbi.nlm.nih.gov/snp/">dbSNP</a> (common human variants) or from published population genomic studies deposited in <a href="https://www.ebi.ac.uk/ena/browser/home">ENA</a> or <a href="https://www.ncbi.nlm.nih.gov/sra">SRA</a>.</li>
</ul>
<p>For a small test run, a handful of transcripts with a few variants each is enough to work through the pipeline end-to-end without waiting on long computations.</p>
</section>
<section id="step-1-preparing-the-input" class="level2">
<h2 class="anchored" data-anchor-id="step-1-preparing-the-input">Step 1: Preparing the input</h2>
<p>The input to this pipeline is a table of variants with these columns: transcript ID, position within the transcript, reference allele, and alternate allele. It looks something like this:</p>
<pre><code>transcript_id       position    ref     alt
TRANSCRIPT_001      152         A       G
TRANSCRIPT_001      340         C       T
TRANSCRIPT_002      88          G       A</code></pre>
<p>Most variant callers (GATK, bcftools, etc.) report variants in genome coordinates, which won’t work here because we need positions within the transcript. To convert genome coordinates to transcript coordinates, use a tool like SnpEff (<span class="citation" data-cites="Cingolani2012-zm">Cingolani et al. (<a href="#ref-Cingolani2012-zm" role="doc-biblioref">2012</a>)</span>) or VEP with your reference GTF. Both will annotate each variant with its transcript-level position, and you pull that field out for the variant table.</p>
<p>Once you have transcript-coordinate variants, some additional filtering is usually appropriate. Common filters at this stage:</p>
<ul>
<li>Coding SNPs only, if you’re focused on the ORF rather than UTRs</li>
<li>Synonymous SNPs only, if you specifically want variants that don’t change the protein</li>
<li>A minor allele frequency cutoff, to skip rare variants where you don’t have enough observations for a meaningful comparison</li>
</ul>
<p>Whether to keep UTR variants depends on the biological question. UTRs often contain regulatory structure, so if you have reason to think UTR structure matters in your system, don’t filter them out by default.</p>
<p>One more thing to watch out for: if a gene is on the reverse strand of the genome, the ref and alt alleles from your variant caller are given relative to the genomic strand, not the transcript strand. When you’re substituting alleles into the transcript sequence, you need the transcript-strand version of the allele. Most variant annotation tools (SnpEff, VEP) will output a strand-corrected allele in their transcript-level output, but it’s worth double-checking that whatever field you’re using is actually strand-corrected. If ref/alt end up flipped for reverse-strand genes, everything downstream will look wrong.</p>
</section>
<section id="step-2-generating-reference-and-alternate-sequences" class="level2">
<h2 class="anchored" data-anchor-id="step-2-generating-reference-and-alternate-sequences">Step 2: Generating reference and alternate sequences</h2>
<p>For each variant you need two sequences: the reference sequence (as it appears in the FASTA) and the alternate sequence, in which the alternate allele has been substituted at the variant position. Here’s how to do this in R using the <code>Biostrings</code> package for a single variant:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Biostrings)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the transcript FASTA</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>transcripts <span class="ot">&lt;-</span> <span class="fu">readDNAStringSet</span>(<span class="st">"transcripts.fa"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Info for a single variant. In a real analysis this would go inside a loop</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># over your variant table.</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>transcript_id <span class="ot">&lt;-</span> <span class="st">"TRANSCRIPT_001"</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>position <span class="ot">&lt;-</span> <span class="dv">152</span>          <span class="co"># position in the transcript, not the genome</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>ref_allele <span class="ot">&lt;-</span> <span class="st">"A"</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>alt_allele <span class="ot">&lt;-</span> <span class="st">"G"</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Pull the reference sequence for this transcript</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>ref_seq <span class="ot">&lt;-</span> transcripts[[transcript_id]]</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Sanity check: the base at that position should match ref_allele.</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="co"># If this fails, something is off with the coordinates.</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">as.character</span>(ref_seq[position]) <span class="sc">==</span> ref_allele)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Copy ref and substitute the alt base to build the alternate sequence</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>alt_seq <span class="ot">&lt;-</span> ref_seq</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>alt_seq[position] <span class="ot">&lt;-</span> <span class="fu">DNAString</span>(alt_allele)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Keep the <code>stopifnot</code> check. Coordinate mismatches (off-by-one errors, 0-indexed versus 1-indexed positions, cDNA versus CDS coordinates) are easy to introduce, and much easier to catch here than to discover later when all your structures are wrong.</p>
<p>For genes with multiple variants of interest, there are two approaches:</p>
<ul>
<li><strong>One variant at a time</strong>: compare ref versus alt for each variant independently. Simpler, and usually a good starting point.</li>
<li><strong>All combinations</strong>: for a gene with <span class="math inline">\(N\)</span> variants, generate all <span class="math inline">\(2^N\)</span> combinations of ref/alt alleles and compare each combination to the all-reference combination. This approach can pick up cases where variants interact structurally, but it grows exponentially — 10 variants means 1024 combinations — so it gets expensive fast.</li>
</ul>
<p>Whichever approach you use, write all sequences to a single FASTA for the next step. Label the headers so you can match structures back to variants later:</p>
<pre><code>&gt;TRANSCRIPT_001_pos152_REF
&gt;TRANSCRIPT_001_pos152_ALT</code></pre>
<p>One thing to note: <code>RNAfold</code> expects RNA sequences (U instead of T). Because transcript FASTAs are usually distributed as DNA, you’ll need to convert T’s to U’s before writing the input file.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert DNA to RNA (T -&gt; U) before passing sequences to RNAfold</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>rna_seq <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"T"</span>, <span class="st">"U"</span>, <span class="fu">as.character</span>(dna_seq))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="step-3-folding-sequences-with-rnafold" class="level2">
<h2 class="anchored" data-anchor-id="step-3-folding-sequences-with-rnafold">Step 3: Folding sequences with RNAfold</h2>
<p><code>RNAfold</code> takes a FASTA of RNA sequences and predicts the minimum free energy (MFE) secondary structure of each. The structure comes out in dot-bracket notation, which is just a string of <code>(</code>, <code>)</code>, and <code>.</code> characters indicating which positions pair with which. The free energy (in kcal/mol) is reported next to the structure.</p>
<p>The basic command:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fold sequences, write structures, no PostScript images</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="ex">RNAfold</span> <span class="at">--noPS</span> <span class="op">&lt;</span> sequences.fa <span class="op">&gt;</span> structures.txt</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The <code>--noPS</code> flag turns off the PostScript image output. Without it, <code>RNAfold</code> generates a <code>.ps</code> file per sequence, which is useful for inspecting individual structures but produces a lot of files when running at scale.</p>
<p>The output has three lines per input sequence: the header, the sequence, and the dot-bracket structure followed by the MFE in parentheses.</p>
<pre><code>&gt;TRANSCRIPT_001_pos152_REF
AUGCUAGCUAGCUACGUACGUACGUAGCUAGCUAG...
(((((....)))))..(((....)))........  (-8.20)
&gt;TRANSCRIPT_001_pos152_ALT
AUGCUAGCUAGCUACGUACGGACGUAGCUAGCUAG...
(((((....)))))..(((....)))((...))..  (-9.10)</code></pre>
<p>The MFE value tells you how stable the structure is: more negative means more stable. If the reference structure folds to -8.2 kcal/mol and the alternate folds to -9.1 kcal/mol, the alternate is slightly more stable. The difference between the two MFEs, sometimes called ΔMFE, is a separate metric from the structural distance we’ll compute in Step 4. Two structures can have similar MFEs but look very different, or have similar shapes but different stabilities. Depending on your question you may care about one, the other, or both.</p>
<p>A few practical considerations:</p>
<p><strong>Temperature.</strong> The default folding temperature is 37°C. This is often reasonable, but for organisms that live at other temperatures (marine species being a common example) it may be more appropriate to fold at a temperature closer to the physiological one. The <code>-T</code> flag sets the temperature in degrees Celsius:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fold at 10°C</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="ex">RNAfold</span> <span class="at">-T</span> 10 <span class="at">--noPS</span> <span class="op">&lt;</span> sequences.fa <span class="op">&gt;</span> structures_10C.txt</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>If your question is specifically about thermal stability, fold at multiple temperatures and compare.</p>
<p><strong>Long sequences.</strong> Very long transcripts (roughly longer than 5000 nucleotides) take substantially longer to fold and can approach memory limits. One option is to fold a window of sequence around each variant rather than the whole transcript. A few hundred nucleotides on either side of the variant is a common choice. Whatever window size you pick, use the same size for every variant so the comparisons stay consistent.</p>
<p><strong>Running at scale.</strong> <code>RNAfold</code> is easy to parallelize because each sequence is folded independently of the others. On a compute cluster, a SLURM job array where each task folds a chunk of sequences works well. Locally, tools like <code>xargs -P</code> or GNU <code>parallel</code> provide similar parallelism.</p>
</section>
<section id="step-4-comparing-structures-with-rnadistance" class="level2">
<h2 class="anchored" data-anchor-id="step-4-comparing-structures-with-rnadistance">Step 4: Comparing structures with RNAdistance</h2>
<p><code>RNAdistance</code> compares two dot-bracket structures and returns a single number representing how different they are. By default it uses tree edit distance, which represents each structure as a tree and counts the minimum number of edit operations needed to turn one tree into the other.</p>
<p>The input is a text file with two structures per comparison, one per line:</p>
<pre><code>(((((....)))))..(((....))).......
(((((....)))))..(((....)))((...))..</code></pre>
<p>Then run:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One distance per pair of structures</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="ex">RNAdistance</span> <span class="op">&lt;</span> structure_pairs.txt <span class="op">&gt;</span> distances.txt</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>You get one distance value per pair. A distance of 0 means the two structures are identical, and larger distances mean more different. What counts as “large” depends on the length of the sequences involved, which is why the next step is to normalize.</p>
<p>For the all-combinations case (multiple variants per gene, each combination compared to all-ref), stack the pairs in the input file:</p>
<pre><code>&lt;all-ref structure&gt;
&lt;combination 1 structure&gt;
&lt;all-ref structure&gt;
&lt;combination 2 structure&gt;
...</code></pre>
<p><code>RNAdistance</code> outputs one distance per pair, in the same order they appeared in the input.</p>
</section>
<section id="worked-example-a-single-variant-end-to-end" class="level2">
<h2 class="anchored" data-anchor-id="worked-example-a-single-variant-end-to-end">Worked example: a single variant end-to-end</h2>
<p>To make the pipeline concrete, here’s a small worked example for a single variant. Say we have a transcript <code>TRANSCRIPT_042</code> of length 480 nucleotides, and a single SNP at position 215 (ref = A, alt = G). We’d generate two sequences (ref and alt), fold each with <code>RNAfold</code>, then run <code>RNAdistance</code> on the two structures.</p>
<p>The MFE outputs from <code>RNAfold</code> might look something like this:</p>
<pre><code>&gt;TRANSCRIPT_042_pos215_REF
...
............(((((....)))))..(((....))).......  (-142.30)
&gt;TRANSCRIPT_042_pos215_ALT
...
............(((((....)))))..(((....)))((...))..  (-135.70)</code></pre>
<p>The reference structure has an MFE of -142.3 kcal/mol and the alternate has -135.7 kcal/mol, so the alternate is slightly less stable (ΔMFE = 6.6 kcal/mol).</p>
<p>Running <code>RNAdistance</code> on the two structures gives a raw distance of, say, 18. To make that comparable across genes of different lengths, we divide by the transcript length:</p>
<pre><code>raw RNA distance         = 18
transcript length        = 480 nt
normalized distance      = 18 / 480 = 0.0375
ΔMFE                     = 6.6 kcal/mol</code></pre>
<p>So this single variant has a normalized RNA distance of 0.0375 and a ΔMFE of 6.6 kcal/mol. Whether that counts as a large or small change depends on the distribution across your full candidate set — but this is the kind of per-variant summary you’d end up with once you’ve run the pipeline.</p>
</section>
<section id="step-5-normalizing-the-distance-score" class="level2">
<h2 class="anchored" data-anchor-id="step-5-normalizing-the-distance-score">Step 5: Normalizing the distance score</h2>
<p>Raw RNA distances aren’t directly comparable across genes because longer sequences can accommodate more possible structural variation. A raw distance of 15 in a 500 nt transcript is a much bigger relative change than the same value in a 3000 nt transcript, so we need to normalize before pooling or ranking distances across genes.</p>
<p>The simplest approach, and the one we use, is to divide the raw distance by the length of the transcript in nucleotides:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Structural change per nucleotide</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>normalized_distance <span class="ot">&lt;-</span> raw_distance <span class="sc">/</span> transcript_length</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This is easy to compute and easy to interpret. The main caveat is that the relationship between length and maximum possible distance isn’t strictly linear, so length normalization is an approximation rather than a formal correction. For a first pass at the data it works well. More rigorous approaches (such as comparing observed distances against a null distribution generated by folding shuffled sequences) are possible but come at a significant computational cost.</p>
</section>
<section id="practical-notes-and-caveats" class="level2">
<h2 class="anchored" data-anchor-id="practical-notes-and-caveats">Practical notes and caveats</h2>
<p><strong>Scaling.</strong> Running this pipeline on thousands of variants is feasible on a compute cluster. Both folding and distance calculation parallelize cleanly across variants, so SLURM job arrays are a straightforward way to organize the work.</p>
<p><strong>MFE is one structure, not the ensemble.</strong> <code>RNAfold</code> returns the single minimum free energy structure, but the actual mRNA in a cell exists as an ensemble of structures. For cases where the MFE structure is very sensitive to small sequence changes, the partition function output (<code>RNAfold -p</code>) gives you base-pair probabilities and ensemble diversity metrics that show a fuller picture. Sometimes the MFE flips dramatically between ref and alt but the ensemble as a whole looks similar, and those cases are worth flagging.</p>
<p><strong>ΔMFE tells you a different thing than RNA distance.</strong> The RNA distance quantifies how different two structures look, while ΔMFE (the difference in minimum free energy between the ref and alt structures) tells you how much the stability of the folded structure changed. Two structures can look quite different but have similar MFEs, or look almost the same but differ in stability. Depending on what you think the variant is doing biologically, one or both may be relevant. It’s often useful to track both alongside each variant, since they capture different aspects of the structural effect.</p>
<p><strong>Distance is a candidate score, not evidence of function.</strong> A high RNA distance means the predicted structure changed, but it doesn’t mean the mRNA behaves differently in the cell. To actually establish a functional effect you need expression data, ribosome profiling, or direct experimental characterization. The distance score is best treated as a way to prioritize which candidates to follow up on.</p>
<p><strong>Ambiguous sequence.</strong> If the transcript FASTA has Ns or IUPAC ambiguity codes near a variant, <code>RNAfold</code> will typically either fail or produce an unreliable structure. Filter these out during input preparation.</p>
</section>
<section id="where-to-go-from-here" class="level2">
<h2 class="anchored" data-anchor-id="where-to-go-from-here">Where to go from here</h2>
<p>Once you have normalized RNA distance scores for your variants, several downstream analyses are possible:</p>
<ul>
<li><strong>Permutation tests</strong>: compare your observed distances against a null distribution built from randomly-selected variant positions in the same set of transcripts. This tests whether your candidate variants collectively show larger structural effects than expected by chance.</li>
<li><strong>Combining with protein-level scores</strong>: if you also have variant effect predictions from tools like EVCouplings (<span class="citation" data-cites="Hopf2019-jd">Hopf et al. (<a href="#ref-Hopf2019-jd" role="doc-biblioref">2019</a>)</span>), SIFT, or AlphaMissense, combining structure-level and protein-level scores gives a fuller picture of variant impact. This is especially useful when your candidate set includes both synonymous and missense variants.</li>
<li><strong>Cross-population comparisons</strong>: if your candidates came out of a population comparison, ranking genes by the magnitude of structural change gives you a natural starting point for follow-up work or experimental validation.</li>
</ul>
</section>
<section id="session-info" class="level2">
<h2 class="anchored" data-anchor-id="session-info">Session info</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>R version 4.5.3 (2026-03-11)
Platform: aarch64-apple-darwin20
Running under: macOS Sonoma 14.6

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRblas.0.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] htmlwidgets_1.6.4 compiler_4.5.3    fastmap_1.2.0     cli_3.6.6        
 [5] tools_4.5.3       htmltools_0.5.9   otel_0.2.0        rstudioapi_0.18.0
 [9] yaml_2.3.12       rmarkdown_2.31    knitr_1.51        jsonlite_2.0.0   
[13] xfun_0.57         digest_0.6.39     rlang_1.2.0       evaluate_1.0.5   </code></pre>
</div>
</div>
</section>
<section id="references" class="level2">




</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Cingolani2012-zm" class="csl-entry" role="listitem">
Cingolani, Pablo, Adrian Platts, Le Lily Wang, Melissa Coon, Tung Nguyen, Luan Wang, Susan J Land, Xiangyi Lu, and Douglas M Ruden. 2012. <span>“A Program for Annotating and Predicting the Effects of Single Nucleotide Polymorphisms, <span>SnpEff</span>: <span>SNPs</span> in the Genome of Drosophila Melanogaster Strain <span class="nocase">w1118</span>; Iso-2; Iso-3: <span>SNPs</span> in the Genome of Drosophila Melanogaster Strain w <span class="math inline">\(^{1118}\)</span> ; Iso-2; Iso-3.”</span> <em>Fly (Austin)</em> 6 (2): 80–92.
</div>
<div id="ref-Hopf2019-jd" class="csl-entry" role="listitem">
Hopf, Thomas A, Anna G Green, Benjamin Schubert, Sophia Mersmann, Charlotta P I Schärfe, John B Ingraham, Agnes Toth-Petroczy, et al. 2019. <span>“The <span>EVcouplings</span> Python Framework for Coevolutionary Sequence Analysis.”</span> <em>Bioinformatics</em> 35 (9): 1582–84.
</div>
<div id="ref-Lorenz2011-yw" class="csl-entry" role="listitem">
Lorenz, Ronny, Stephan H Bernhart, Christian Höner Zu Siederdissen, Hakim Tafer, Christoph Flamm, Peter F Stadler, and Ivo L Hofacker. 2011. <span>“<span>ViennaRNA</span> Package 2.0.”</span> <em>Algorithms Mol. Biol.</em> 6 (1): 26.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./FUN_02_DNA_methylation.html" class="pagination-link" aria-label="DNA Methylation Assessment">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">DNA Methylation Assessment</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/MarineOmics/marineomics.github.io/edit/main/MOL_01_RNAdist_tutorial.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/MarineOmics/marineomics.github.io/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>